stryker4s {
  scala-dialect = "scala3"
  mutate = [
    "src/main/scala/**/*.scala",
    "!src/main/scala/**/Main.scala",
    "!src/main/scala/**/UnoPlay.scala",
    "!src/main/scala/**/SwingGui.scala",
    "!src/main/scala/**/FileIOUsageExample.scala"
  ]
}